version: '3.9'
services:
  server:
    container_name: server
    build:
      dockerfile: Dockerfile
    restart: on-failure
    command: yarn start:dev
    ports:
      - 3000:3000
    volumes:
      - ./:/usr/src/app
